server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leafy
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # hibernate 사용 설정
    hibernate:
      # Hibernate가 데이터베이스 스키마를 자동으로 생성하거나 업데이트할지 여부를 설정
      # 예를들어, create로 설정하면 if exist drop table 해주고 다시 생성해줌
      # 로컬, 개발에서는 create, update 해도되지만 운영에서는 none으로 설정해야함
      ddl-auto: none
    properties:
      hibernate:
        # 쿼리 출력할때 format에 맞출지 여부
        format_sql: true
        # jpa로 생성되는 쿼리를 콘솔에 출력할지 여부
        show_sql: true
        # 엔티티들을 로딩할 때 부모 엔티티를 1번 조회할때 연관된 자식 엔티티를 N번 조회해야하므로 성능 저하가 발생
        # batch 크기를 100으로 설정하면 자식 엔티티 100개를 한번에 로딩하게 됨
        default_batch_fetch_size: 100
        # 쿼리에 어떤 실행을 하려는지 주석으로 표시
        use_sql_comments: true
    # 트랜잭션을 종료할 때 영속성 컨텍스트를 요청 처리가 완료될 때까지 열어두는지 여부
    open-in-view: false
    # 기본적으로 어플리케이션 시작 시점에 데이터 소스를 초기화하는데
    # true로 설정하면 데이터베이스 연결 시점에 초기화함
    defer-datasource-initialization: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
