#spring:






#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        format_sql: true
#        show_sql: true
#        default_batch_fetch_size: 100
#        use_sql_comments: true
#    open-in-view: false
#    defer-datasource-initialization: true
